from datetime import time

hora_dayin = time(hour=7, minute=0)
hora_rd = time(hour=8, minute=45)
hora_burn1 = time(hour=9, minute=45)
hora_burn2 = time(hour=12, minute=30)
hora_burn3 = time(hour=15, minute=0)
hora_agenda_pre = time(hour=16, minute=0)
hora_agenda_pre_eq = time(hour=15, minute=44)
hora_agenda = time(hour=16, minute=18)
hora_agenda_sem = time(hour=16, minute=25)
hora_burn4 = time(hour=16, minute=40)
hora_dayout = time(hour=17, minute=10)
hora_newday = time(hour=17, minute=30)
hora_food = time(hour=11, minute=0)
hora_pay = time(hour=14, minute=0)
hora_deploy = time(hour=6, minute=30)
